apiVersion: apps/v1 #1
kind: Deployment #2
metadata: #3
  name: nodejsmysql-deployment #4
spec: #5
  replicas: 2 #6
  selector: #7
    matchLabels: #7
      app: nodejsmysql #7
  template: #8
    metadata: #9
      labels: #10
        app: nodejsmysql #11
    spec: #12
      containers: #13
      - name: test2 #14
        image: panagiotispap/nodejs-mysql #15
        ports: #16
        - containerPort: 30001 #17
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsmysql
spec:
  selector:
    app: nodejsmysql
  type: NodePort # remove if using ClusterIp
  ports:
    - port: 30001
      targetPort: 30001
      nodePort: 32100